# Generated by Django 4.1.2 on 2023-02-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='net_price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
